In [1]:
import pandas as pd
import numpy as np
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.

In [2]:
As7 ="data science is one of the most important fields of science this is one of the best data science courses data scientists analyze data"

In [3]:
#Stop Words
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
tokens = word_tokenize(As7.lower())
print("Tokens:", tokens)
english_stopwords = stopwords.words('english')
tokens_wo_stopwords = [t for t in tokens if t not in english_stopwords]
print("Text without stop words:", " ".join(tokens_wo_stopwords))

Tokens: ['data', 'science', 'is', 'one', 'of', 'the', 'most', 'important', 'fields', 'of', 'science', 'this', 'is', 'one', 'of', 'the', 'best', 'data', 'science', 'courses', 'data', 'scientists', 'analyze', 'data']
Text without stop words: data science one important fields science one best data science courses data scientists analyze data

In [4]:
# Tokens
words_set = set()

for doc in  tokens:
    words = doc.split(' ')
    words_set = words_set.union(set(words))
    
print('Number of words in the As7:',len(words_set))
print('The words in the As7: \n', words_set)

Number of words in the As7: 14
The words in the As7:
 {'the', 'of', 'scientists', 'courses', 'analyze', 'most', 'data', 'important', 'one', 'best', 'science', 'is', 'fields', 'this'}

In [5]:
# Term Frequency
n_docs = len(tokens)
n_words_set = len(words_set)
df_tf = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=words_set)
for i in range(n_docs):
    words = tokens[i].split(' ')
    for w in words:
        df_tf[w][i] = df_tf[w][i] + (1 / len(words))
df_tf

,the,of,scientists,courses,analyze,most,data,important,one,best,science,is,fields,this
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
14,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
19,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
print("IDF of: ")

idf = {}

for w in words_set:
    k = 0
    
    for i in range(n_docs):
        if w in tokens[i].split():
            k += 1
            
    idf[w] =  np.log10(n_docs / k)
    
    print(f'{w:>15}: {idf[w]:>10}' )

IDF of:
            the: 1.0791812460476249
             of: 0.9030899869919435
     scientists: 1.380211241711606
        courses: 1.380211241711606
        analyze: 1.380211241711606
           most: 1.380211241711606
           data: 0.7781512503836436
      important: 1.380211241711606
            one: 1.0791812460476249
           best: 1.380211241711606
        science: 0.9030899869919435
             is: 1.0791812460476249
         fields: 1.380211241711606
           this: 1.380211241711606

In [7]:
import nltk
nltk.download('averaged_perceptron_tagger')
stop_words = set(stopwords.words('english'))

tokenized = sent_tokenize(As7)
for i in tokenized:
     
    wordsList = nltk.word_tokenize(i)
 
    wordsList = [w for w in wordsList if not w in stop_words]
    tagged = nltk.pos_tag(wordsList)
 
    print(tagged)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[('data', 'NNS'), ('science', 'NN'), ('one', 'CD'), ('important', 'JJ'), ('fields', 'NNS'), ('science', 'VB'), ('one', 'CD'), ('best', 'JJS'), ('data', 'NN'), ('science', 'NN'), ('courses', 'NNS'), ('data', 'VBP'), ('scientists', 'NNS'), ('analyze', 'VBP'), ('data', 'NNS')]

In [8]:
# Stemming and Lemmatization
porter_stemmer = PorterStemmer()

nltk_tokens = nltk.word_tokenize(As7)
for w in nltk_tokens:
       print("Actual:- %s       Stem:- %s"  %(w,porter_stemmer.stem(w)))

Actual:- data       Stem:- data
Actual:- science       Stem:- scienc
Actual:- is       Stem:- is
Actual:- one       Stem:- one
Actual:- of       Stem:- of
Actual:- the       Stem:- the
Actual:- most       Stem:- most
Actual:- important       Stem:- import
Actual:- fields       Stem:- field
Actual:- of       Stem:- of
Actual:- science       Stem:- scienc
Actual:- this       Stem:- thi
Actual:- is       Stem:- is
Actual:- one       Stem:- one
Actual:- of       Stem:- of
Actual:- the       Stem:- the
Actual:- best       Stem:- best
Actual:- data       Stem:- data
Actual:- science       Stem:- scienc
Actual:- courses       Stem:- cours
Actual:- data       Stem:- data
Actual:- scientists       Stem:- scientist
Actual:- analyze       Stem:- analyz
Actual:- data       Stem:- data

In [9]:
lemmatizer = WordNetLemmatizer()

In [10]:
for w in nltk_tokens:
       print("Actual:- %s       Stem:- %s"  %(w,lemmatizer.lemmatize(w)))

Actual:- data       Stem:- data
Actual:- science       Stem:- science
Actual:- is       Stem:- is
Actual:- one       Stem:- one
Actual:- of       Stem:- of
Actual:- the       Stem:- the
Actual:- most       Stem:- most
Actual:- important       Stem:- important
Actual:- fields       Stem:- field
Actual:- of       Stem:- of
Actual:- science       Stem:- science
Actual:- this       Stem:- this
Actual:- is       Stem:- is
Actual:- one       Stem:- one
Actual:- of       Stem:- of
Actual:- the       Stem:- the
Actual:- best       Stem:- best
Actual:- data       Stem:- data
Actual:- science       Stem:- science
Actual:- courses       Stem:- course
Actual:- data       Stem:- data
Actual:- scientists       Stem:- scientist
Actual:- analyze       Stem:- analyze
Actual:- data       Stem:- data